<?php

namespace ContainerHcHmI9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GukMh_SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gukMh.S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gukMh.S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ligneCommande' => ['privates', '.errored..service_locator.gukMh.S.App\\Entity\\LigneCommande', NULL, 'Cannot autowire service ".service_locator.gukMh.S": it references class "App\\Entity\\LigneCommande" but no such service exists.'],
        ], [
            'ligneCommande' => 'App\\Entity\\LigneCommande',
        ]);
    }
}
