<?php

namespace ContainerHcHmI9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneCommandeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\LigneCommandeType' shared autowired service.
     *
     * @return \App\Form\LigneCommandeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/LigneCommandeType.php';

        return $container->privates['App\\Form\\LigneCommandeType'] = new \App\Form\LigneCommandeType();
    }
}
