<?php

namespace ContainerC6Uyp85;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneCommande2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gukMh.S.App\Entity\LigneCommande' shared service.
     *
     * @return \App\Entity\LigneCommande
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gukMh.S": it references class "App\\Entity\\LigneCommande" but no such service exists.');
    }
}
