<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHcHmI9m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHcHmI9m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHcHmI9m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHcHmI9m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHcHmI9m\App_KernelDevDebugContainer([
    'container.build_hash' => 'HcHmI9m',
    'container.build_id' => '210b578c',
    'container.build_time' => 1649946742,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHcHmI9m');
